[package]

name = "eant2"
version = "0.0.1"
authors = ["pengowen123 <pengowen816@gmail.com>"]

[[bin]]

name = "eant2"

[dependencies]

rand = "0.3"
cmaes = { git = "https://github.com/pengowen123/cmaes" }
